### ISSUE TITLE
White dot in the center

### ISSUE THREAD

**Issue by czw90130** [RaiMan/sikulix4python#1]
There will be a white dot in the center of the screen when using
`java -jar path-to/sikulixapi.jar -p`
on Windows 10. 
This may cause OCR failure.
Not tested with pattern recognition. But I think it's best to remove it.

**Comment by czw90130** [comment]
Should I put the issues here or in https://github.com/RaiMan/SikuliX1/issues ？

**Comment by RaiMan** [comment]
LOL, never seen this before: it is the background positioner for the popup and becomes visible on non-white backgrounds if you move the popup out of way.
This anyways is only a helper for now, to get a chance to stop the server.
I think I will try to change this to the usage of a hot-key (probably alt-shift-c)

**Comment by RaiMan** [comment]
... and yes: everything related to real Python usage should be reported here for now.

Be aware: very early stage, very experimental.

**Comment by RaiMan** [comment]
I have removed the popup and added the possibility to stop the server with the stop hotkey.

**Comment by czw90130** [comment]
Very Cool Project! Thank you!
