### ISSUE TITLE
hi RaiMan，i just use sikulix4python on my linux systerm,and i find a question

### ISSUE THREAD

**Issue by rainysweet** [RaiMan/sikulix4python#10]
i use pycharm in my linux systerm for AutoTest, now i find a question
click(img), can't find the img  . the screenshot below:
![202201121806530252170260114436FD](https://user-images.githubusercontent.com/10592255/149121377-77f12bcc-138e-4554-97f1-5f3475c9f32a.jpeg)
![202201121807220252180010169327FD](https://user-images.githubusercontent.com/10592255/149121378-7e18409e-3638-4e06-8a23-f4a98614037b.jpg)

the same code  works very well on MacOS and Win autoText ~  

so  thx u help 
      ~ tips:poor english don't mind~ 😄

**Comment by rainysweet** [comment]
i confirm the Img is ok ~  because i use the sikulix-ide can find the image ~

**Comment by RaiMan** [comment]
I guess the problem are the non-ASCII characters in the image name:
<img width="283" alt="Bildschirmfoto 2022-01-12 um 14 08 06" src="https://user-images.githubusercontent.com/586370/149146272-0ad4505b-759e-42fe-b176-27f83fe4a608.png">
<img width="552" alt="Bildschirmfoto 2022-01-12 um 14 08 39" src="https://user-images.githubusercontent.com/586370/149146300-b266a7b3-d64f-45ff-803c-465a038fb699.png">

**Comment by rainysweet** [comment]
sad, i just change the image name to english or number  but  as  the same. 
but i find use Region ,sikulix works very well. the image below:
![202201130945380252180090173228FD](https://user-images.githubusercontent.com/10592255/149251526-e4d59c01-daa4-42f7-b60f-5fdbe8e3ba0e.png)
![202201130944440252180030100979FD](https://user-images.githubusercontent.com/10592255/149251528-d378ef71-ab53-4f4e-85b9-3bbe91c8c351.png)

**Comment by RaiMan** [comment]
ok, then try with an absolute path.

Or resolve the working directory at the Python level to a string and create an absolute filename programmatically.

Another option is to use `ImagePath.setBundlePath()`.

**Comment by rainysweet** [comment]
Thank you so much ~   i fix it ~
