### ISSUE TITLE
The relative path of img.png does not work.

### ISSUE THREAD

**Issue by clobob** [RaiMan/sikulix4python#2]
Win10+jdk1.8+sikulix 1.1.4

Try to run the given code, the relative path does not work as expected.
Here is the debug info from sikulixapi:
![image](https://user-images.githubusercontent.com/10508051/61344988-dfc72d80-a885-11e9-88f7-24d70042ae70.png)

corresponding to the code:

_img = "img.png"
scr.exists(img,3.0)_

**Comment by RaiMan** [comment]
sorry, no support here currently.
