### ISSUE TITLE
Detecting Ui controls like button, textbox, checkbox

### ISSUE THREAD

**Issue by SaddamBInSyed** [RaiMan/sikulix4python#3]
@RaiMan 
thanks for your work.

I want to highlight another application UI controls from my application based on the mouse position.

example : when mouse moves over the button then I want to highlight the button region(rect)?

How can I do the same with the help of your library?

ref:
https://dsp.stackexchange.com/questions/1471/how-can-i-detect-buttons-in-a-gui-of-an-app-with-pattern-detection-using-python

please advise.

**Comment by RaiMan** [comment]
Currently not a feature of SikuliX.

You have to intelligently use the OpenCV features to detect elements in an image (basically edge-detection).

Might be available in a future version.
