### ISSUE TITLE
highlight  does not exist?

### ISSUE THREAD

**Issue by laolyu** [RaiMan/sikulix4python#8]
when I run the example,
scr.getCenter().grow(100).highlight(2)
I  get the Trace:
py4j.Py4JException: Method highlight([class java.lang.Integer]) does not exist
and I cannot understand  what is the mean of"
one gets method missing, if signatures do not fit
"

**Comment by RaiMan** [comment]
Sorry, I cannot help you currently.

My work with this project is pausing since more than 2 years.
You have to find a solution yourself.
